name: ErisEssentials
version: ${project.version}
main: torchdevelopments.erisessentials.Core.ErisEssentials
api-version: 1.13
authors: [Erisdar]
description: Plugin for basic server functionality such as land protection, chest protection and player shops
commands:
  fly:
    description: Make youtself fly!
  afk:
    description: Make yourself safe whilst you're afk!
  ec:
    description: Open your Ender Chest
    Aliases: [enderchest]
  inv:
    description: View a target player's inventory
  broadcast:
    description: Broadcast a message to the server
  chest:
    description: Commands to alter chest protection
  barrel:
    description: Commands to alter barrel protection
  furnace:
    description: Commands to alter furnace protection
  invisible:
      description: Make yourself invisible
