name: ErisEssentials
version: 1.0-SNAPSHOT
main: torchdevelopments.erisessentials.Core.ErisEssentials
api-version: 1.13
authors: [Erisdar]
description: Plugin for basic server functionality such as land protection, chest protection and player shops
